version: "3.1"
services:
  course_platform_database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: platform_passwd_UeB1n831
      MYSQL_DATABASE: platform_db
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
